import { PresetAvatarState } from "../../../types";

export const MARIKA_PRESETS: Record<
  "marika-gombitova" | "marika-official" | "marika-atelier",
  Partial<PresetAvatarState> & { name: string; description?: string }
> = {
  "marika-gombitova": {
    name: "Pani Gombitka",
    description: "Classic",
    head: "rounded",
    eyes: "calmBlueGrey",
    eyebrows: "marikaArch",
    nose: "smallButton",
    mouth: "vibrantRedSmall",
    hair: "shortCurlyBob",
    skinTone: "porcelain",
    hairColor: "platinumBlonde",
    body: "marikaSparkleTop",
    bodyColor: "black",
  },
  "marika-official": {
    name: "Pani Gombitka",
    description: "Legendárna",
    head: "rounded",
    eyes: "marikaProfoundBlue",
    eyebrows: "marikaDefinedArch",
    nose: "smallButton",
    mouth: "smirk",
    hair: "marikaBangsUpdo",
    skinTone: "porcelain",
    hairColor: "#F7E7CE",
    body: "marikaOfficialJacket",
    bodyColor: "red",
    texture: "halftone",
  },
  "marika-atelier": {
    name: "Pani Gombitka",
    description: "Ateliér Duše",
    head: "rounded",
    eyes: "marikaAtelier",
    eyebrows: "marikaArch",
    nose: "smallButton",
    mouth: "smirkRed",
    hair: "marikaAtelier",
    skinTone: "porcelain",
    hairColor: "#E3E0B5",
    body: "marikaAtelier",
    bodyColor: "black",
    extras: "marikaBlush",
    accessories: "marikaAtelierEarrings",
    texture: "halftone",
  },
};
