export const HairIds = [
  "bald",
  "buzzCut",
  "flatTopShort",
  "shortJaggedCrop",
  "sidePartShort",
  "bobCutSharp",
  "bobCutStraight",
  "jaggedFringeBob",
  "bowlCutRound",
  "sharpBobYellowHighlight",
  "shortCurlyBob",
  "longStraightLayered",
  "longLocs",
  "messySideSwept",
  "roundedCurls",
  "trapezoidCut",
  "roundedMiddlePart",
  "puffyMiddlePart",
  "heartMiddlePart",
  "sweptFringe",
  "singleTopKnot",
  "doubleSpaceBuns",
  "lowPonytail",
  "largeAfro",
  "spikyMohawk",
  "shavedSidesLongBack",
  "aviatorFlaps",
  "texturedPompadour",
  "largeHairBow",
  "detailedHairBow",
] as const;

export type HairId = (typeof HairIds)[number];
